# Dev-specific overrides
server.port=8014
spring.datasource.url=jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_UPPER=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.flyway.enabled=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=INFO
logging.level.com.example.usersapi=DEBUG
logging.level.org.springframework.security=DEBUG
