ALTER TABLE users
    ADD COLUMN password VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN role VARCHAR(20) NOT NULL DEFAULT 'USER';

ALTER TABLE users
    ADD CONSTRAINT chk_users_role CHECK (role IN ('USER', 'ADMIN'));
